# Site settings

url: "http://fernandolkf.github.io"
title: "{Fernando de Lucca Siqueira}"
description: "Personal blog and website of Fernando de Lucca Siqueira."
keywords: "fernandolkf, fernando, de lucca, siqueira, computer science, moving objects trajectory, mobile robots, gaming, fenixdown"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-66906058-1"
disqus-shortname: "fernandolkf"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Career: 'career'
  Blog: 'blog'
  Contact: 'contact'

background-img: "/img/intro-bg.png"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/logo_ufsc_pgeas.png"
    date: "September 2015 - July 2016"
    description: "Substitute Teacher @ <a href=\"http://www.ufsc.br\" target=\"_blank\">Department of Systems Engineering and Automation</a>, Universidade Federal de Santa Catarina"
  - image: "/img/career/logo_cnr.png"
    date: "February 2013 - April 2013"
    description: "Visitor researcher @ <a href=\"http://www.isti.cnr.it\" target=\"_blank\"> Consiglio Nazionale delle Ricerche</a> Pisa, Italy"
  - image: "/img/career/logo_ufsc_pgeas.png"
    date: "March 2012 - March 2017"
    description: "PhD degree on Systems Engineering and Automation @ <a href=\"http://pgeas.ufsc.br\" target=\"_blank\"> Department of Systems Engineering and Automation,</a>  Universidade Federal de Santa Catarina"
  - image: "/img/career/logo_ufsc_ppgcc.png"
    date: "March 2010 - February 2012"
    description: "Master degree on Computer Science  @ <a href=\"http://ppgcc.posgrad.ufsc.br\" target=\"_blank\">Department of Informatics and Statistics,</a> Universidade Federal de Santa Catarina"
  - image: "/img/career/logo_paripassu.png"
    date: "September 2009 - February 2010"
    description: "Software developer @ <a href=\"http://http://www.paripassu.com.br\" target=\"_blank\">Paripassu</a>"  
  - image: "/img/career/logo_ufsc_lapesd.png"
    date: "Jan 2008 - August 2009"
    description: "Scientific initiation @ <a href=\"http://www.lapesd.inf.ufsc.br\" target=\"_blank\">LaPeSD</a> developing the <a href=\"http://www.literaturabrasileira.ufsc.br\" target=\"_blank\">Digital Library of Portuguese Literature</a>"
  - image: "/img/career/logo_ufsc_cco.png"
    date: "August 2005 - December 2009"
    description: "Bachelor studies @ <a href=\"http://www.cco.inf.ufsc.br\" target=\"_blank\">Universidade Federal de Santa Catarina</a> on Computer Science"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/fernandolkf"
  - title: "linkedin"
    url: "https://www.linkedin.com/pub/fernando-de-lucca-siqueira/2a/9b7/647"
  - title: "twitter"
    url: "http://twitter.com/fernando_x"


404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
